---
- name: version
  hosts: kubespray
  become: true
  become_method: sudo
  become_user: root
  remote_user: busra
  tasks:
  - name: kubernetes version
    shell: "kubectl version"
    args:
      executable: "/bin/bash"
    register: kv

  - name: output
    debug:
      msg: "{{ kv.stdout_lines }}"

- name: versiondocker
  hosts: kubespray
  become: true
  become_method: sudo
  become_user: root
  remote_user: busra
  tasks:
  - name: docker version
    shell: "docker version"
    args:
      executable: "/bin/bash"
    register: dv

  - name: output
    debug:
      msg: "{{ dv.stdout_lines }}"
